#! /bin/bash
#
# Automatically generated by gen_bash_script.sh
#
# fastbooot - use fastboot to flash images
#

fastbooot ()
{
	local TAG=${TAG:-${FUNCNAME[0]}}

	if [[ $1 == --* ]]; then
		usage
		return 0
	fi

	# place fastboot
	local FASTBOOT='/opt/bin/fastboot'
	if [[ ! -x $FASTBOOT ]]; then
		echo "$TAG: error: invalid $FASTBOOT."
		return 1
	fi
	[[ $UID != 0 ]] && 	FASTBOOT="sudo $FASTBOOT"
	
	# path of imgs
	local imgs_dir
	if [[ -n $1 ]]; then
		imgs_dir=$1
	elif [[ -n $TARGET_PRODUCT ]]; then
		imgs_dir="out/target/product/$TARGET_PRODUCT"
	else
		imgs_dir=$PWD
	fi
	if [[ ! -d $imgs_dir ]]; then
		echo "$TAG: error: $imgs_dir is not a directory."
		return 1
	fi
	
	local imgs=$(cd "$imgs_dir"; ls *.img 2>/dev/null)
	if [[ -z $imgs ]]; then
		echo "$TAG: warning: no image in $imgs_dir."
		return 1
	fi
	
	local -A map=([b]=boot.img
	              [c]=custpack.img
	              [r]=recovery.img
	              [s]=system.img
	              [u]=userdata.img)
	local index='bcrsu'
	local all=
	local def='usb'
	local ret=
	local list=
	local i=

	for ((i=0; i<${#index}; i++)); do
		if echo $imgs | grep ${map[${index:$i:1}]} &> /dev/null; then
			printf "%16s: %s\n" "${map[${index:$i:1}]%.img}" "${index:$i:1}"
			all=$all${index:$i:1}
		fi
	done
	
	for ((i=0; i<${#def}; i++)); do
		if echo $all | grep ${def:i:1} &> /dev/null; then
			ret=$ret${def:i:1}
		fi
	done
	
	read -p "flash which(s)? [default: $ret] " list
	list=${list:-$ret}
	
	for ((i=0; i<${#list}; i++)); do
		if [[ -n ${map[${list:$i:1}]} ]]; then
			$FASTBOOT flash ${map[${list:$i:1}]%.img} "$imgs_dir/${map[${list:$i:1}]}"
		fi
	done

	alert '搞定收工！'

	return $?
}

# Script can be used as a program or a function
if echo $0 | grep -qvE '^[-]?bash'; then

	# Global VARs
	PRO=$(basename "$0")
	TAG=$PRO

	# Show usage
	usage ()
	{
		cat << USAGE_END
usage: $PRO [DIR]

       Use fastboot to flash images.

       Arguments:
         DIR: a directory containing images
USAGE_END

		return 0
	}

	# Main
	fastbooot "$@"
fi
