#! /bin/bash

Processbar()
{
	local _tag=${_tag:-${FUNCNAME[0]}}

	local long=80
	local current=

	printf "[\033[${long}C]%4s%%" 0

	for ((current=0; current<long; current++)); do
		printf "\033[$((6+long-current))D>\033[1D"
		sleep 0.1;
		printf "=\033[$((long-current))C%4s%%" $((100*(current+1)/long))
	done

	echo

	return 0
}

Fraction()
{
	local fmt=${3:-"%3s%% (%${#2}s/$2)"}
	local fmt_back=${4:-"\033[$((${#2}*2+8))D"}

	[[ $1 -gt 0 ]] && printf "$fmt_back"
	printf "$fmt" $((100*$1/$2)) $1
	[[ $1 -eq $2 ]] && echo ', done.'

	return $?
}
